name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.156+156
isar_version: &isar_version ^3.1.8

environment:
  sdk: ">=3.5.2"
  flutter: ">=3.24.2"

dependency_overrides:
  collection: ^1.19.0 # Flutter SDK

dependencies:
  app_links: ^6.3.2
  assorted_layout_widgets: ^9.0.2
  collection: ^1.19.0
  datetime_picker_formfield_new: ^2.1.0
  device_info_plus: ^10.1.2
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  fab_circular_menu_plus: ^0.0.2
  file_picker: ^8.1.2
  flex_color_scheme: ^7.3.1
  floor: ^1.5.0
  flutter_archive: ^6.0.3
  flutter_blue_plus: ^1.32.12
  flutter_circle_color_picker: ^0.3.0
  flutter_layout_grid: ^2.0.7
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  get: ^4.6.6
  group_button: ^5.3.4
  http: ^1.2.2
  http_parser: ^4.1.0
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  listview_utils_plus: ^0.0.3
  loading_overlay: ^0.3.0
  number_selector: ^1.0.7
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  pref: ^2.8.0
  progress_indicators: ^1.0.0
  qr_widget: ^4.1.0
  rxdart: ^0.28.0
  share_files_and_screenshot_widgets: ^1.0.6
  share_plus: ^10.0.2
  soundpool: ^2.4.1
  sqflite: ^2.3.3+1
  string_validator: ^1.1.0
  syncfusion_flutter_charts: ^26.2.14
  timezone: ^0.9.4
  tuple: ^2.0.2
  url_launcher: ^6.3.0
  vector_math: ^2.1.4
  wakelock_plus: ^1.2.8
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^6.8.0
  build_runner: ^2.4.12
  floor_generator: ^1.5.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  mocktail: ^1.0.4
  mock_data: ^2.0.1
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
    - assets/audio/
    - assets/donation/
    - assets/integration/
    - assets/equipment/
