name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a running track.
publish_to: "none"

version: 1.1.21+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: any
  data_connection_checker: any
  datetime_picker_formfield: any
  device_info: any
  expandable: any
  fab_circular_menu: any
  file_picker: ^2.1.6
  floor: ^0.18.0
  flutter_blue: any
  flutter_brand_icons: any
  get: ^3.24.0
  http: ^0.12.2
  http_parser: ^3.1.4
  intl: ^0.16.1
  listview_utils: any
  loading_overlay: any
  meta: ^1.2.4
  preferences: any
  progress_indicators: any
  share_files_and_screenshot_widgets: any
  shared_preferences: any
  sqflite: ^1.3.2+3
  uni_links: any
  url_launcher: any
  wakelock: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.1
  floor_generator: 0.18.0
  integration_test: ^1.0.2+2
  mockito: any
  mock_data: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
