name: track_my_indoor_exercise
description: Recording indoor exercises as if circling in a Velodrome or on a running track.
publish_to: "none"

version: 1.1.5+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  e2e: any
  floor: any
  flutter_blue: any
  flutter_brand_icons: any
  get: any
  http: any
  intl: any
  http_parser: any
  listview_utils: any
  share_files_and_screenshot_widgets: any
  shared_preferences: any
  sqflite: any
  uni_links: any
  url_launcher: any
  wakelock: any
  charts_flutter: any
  preferences: any
  loading_overlay: any
  fab_circular_menu: any
  device_info: any
  expandable: any
  progress_indicators: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: any
  floor_generator: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DSEG7
      fonts:
        - asset: fonts/DSEG7Modern-Bold.ttf
    - family: DSEG14
      fonts:
        - asset: fonts/DSEG14Classic-Bold.ttf
