name: virtual_velodrome_rider
description: Recording virtual rides as if circling in a Velodrome or on a running track.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_blue: any
  e2e: any
  get: any
  sqflite: any
  flutter_brand_icons: any
  intl: any
  http: any
  url_launcher: any
  shared_preferences: any
  uni_links: any
  http_parser: any
  floor: any
  listview_utils: any
  wakelock: any
  flutter:
    sdk: flutter

dev_dependencies:
  floor_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
