name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.53+53

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^4.0.0-nullsafety.1
  bluetooth_enable: 0.1.1
  charts_flutter: any
  data_connection_checker: any
  datetime_picker_formfield: any
  device_info: any
  edit_distance: ^0.4.1
  expandable: any
  fab_circular_menu: any
  file_picker: ^2.1.6
  floor: ^0.18.0
  flutter_blue:
    git:
      url: https://github.com/CsabaConsulting/flutter_blue.git
      ref: patch-3
  flutter_brand_icons: any
  flutter_spinbox: ^0.3.1+2
  get: ^3.24.0
  http: ^0.12.2
  http_parser: ^3.1.4
  intl: ^0.16.1
  listview_utils: any
  loading_overlay: any
  meta: ^1.2.4
  permission_handler: ^5.1.0+2
  preferences: any
  progress_indicators: any
  rxdart: ^0.24.0
  share_files_and_screenshot_widgets: any
  shared_preferences: any
  soundpool: ^1.1.3
  spinner_input: ^0.1.2
  sqflite: ^1.3.2+3
  tuple: ^1.0.3
  uni_links: any
  url_launcher: any
  wakelock: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.1
  floor_generator: ^0.18.0
  integration_test: ^1.0.2+2
  mockito: any
  mock_data: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
  assets:
    - assets/
