name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.55+55

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^4.0.0-nullsafety.1
  charts_flutter: ^0.10.0
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.2
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  fab_circular_menu: ^1.0.2
  file_picker: ^3.0.2+2
  floor: ^1.1.0
  flutter_blue: ^0.8.0
  flutter_brand_icons: ^1.1.0
  get: ^4.1.4
  http: ^0.13.3
  http_parser: ^4.0.0
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  listview_utils:
    git:
      url: https://github.com/WaleedAlrashed/flutter-listutils.git
  loading_overlay: ^0.3.0
  meta: ^1.4.0
  permission_handler: ^8.0.0+2
  preferences: any
  progress_indicators: ^1.0.0
  rxdart: ^0.27.1
  share_files_and_screenshot_widgets: ^1.0.3
  shared_preferences: ^2.0.5
  soundpool: ^2.1.0
  spinner_input: ^0.1.2
  sqflite: ^2.0.0+3
  tuple: ^2.0.0
  uni_links2: ^0.6.0+2
  url_launcher: ^6.0.3
  wakelock: ^0.5.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.12.2
  floor_generator: ^1.1.0
  integration_test: ^1.0.2+2
  mockito: ^5.0.3
  mock_data: ^1.2.8
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
  assets:
    - assets/
