name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.153+153
isar_version: &isar_version ^3.1.0+1

environment:
  sdk: ">=3.3.0-279.0.dev"
  flutter: ">=3.19.0-0.1.pre"

dependency_overrides:
  analyzer: ^6.3.0  # because of isar_generator
  intl: ^0.19.0  # because of syncfusion_flutter_charts

dependencies:
  assorted_layout_widgets: ^9.0.0
  collection: ^1.17.2
  datetime_picker_formfield_new: ^2.1.0
  device_info_plus: ^9.1.1
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  fab_circular_menu_plus: ^0.0.2
  file_picker: ^6.1.1
  flex_color_scheme: ^7.3.1
  floor: ^1.4.2
  flutter_blue_plus:
    git:
      url: https://github.com/CsabaConsulting/flutter_blue_plus.git
      ref: 1684ae4452924c566121337f80c5fed589fd8c41
  flutter_circle_color_picker: ^0.3.0
  flutter_layout_grid: ^2.0.5
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  get: ^4.6.6
  group_button: ^5.3.4
  http: ^1.2.0
  http_parser: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  listview_utils_plus: ^0.0.3
  loading_overlay: ^0.3.0
  number_selector: ^1.0.7
  package_info_plus: ^5.0.1
  path: ^1.9.0
  path_provider: ^2.1.2
  pref: ^2.8.0
  progress_indicators: ^1.0.0
  qr_widget: ^4.1.0
  rxdart: ^0.27.7
  share_files_and_screenshot_widgets: ^1.0.6
  soundpool: ^2.4.1
  sqflite: ^2.3.0
  string_validator: ^1.0.2
  syncfusion_flutter_charts: ^24.1.46+1
  timezone: ^0.9.2
  tuple: ^2.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.2.3
  vector_math: ^2.1.4
  wakelock_plus: ^1.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: *isar_version
  mocktail: ^1.0.3
  mock_data: ^2.0.1
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
    - assets/audio/
    - assets/donation/
    - assets/integration/
    - assets/equipment/
