name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a running track.
publish_to: "none"

version: 1.1.20+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  floor: ^0.18.0
  flutter_blue: any
  flutter_brand_icons: any
  get: ^3.24.0
  http: any
  intl: any
  http_parser: any
  listview_utils: any
  share_files_and_screenshot_widgets: any
  shared_preferences: any
  sqflite: any
  uni_links: any
  url_launcher: any
  wakelock: any
  charts_flutter: any
  preferences: any
  loading_overlay: any
  fab_circular_menu: any
  device_info: any
  expandable: any
  progress_indicators: any
  data_connection_checker: any
  datetime_picker_formfield: any
  file_picker: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.11
  floor_generator: 0.18.0
  integration_test: ^1.0.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DSEG7
      fonts:
        - asset: fonts/DSEG7Modern-Bold.ttf
    - family: DSEG14
      fonts:
        - asset: fonts/DSEG14Classic-Bold.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
