name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.77+77

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^5.0.2
  bluetooth_enable:
    git:
      url: https://github.com/CsabaConsulting/bluetooth_enable.git
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.2
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  file_picker: ^3.0.3
  floor: ^1.1.0
  flutter_blue:
    git:
      url: https://github.com/CsabaConsulting/flutter_blue.git
  flutter_spinbox: ^0.5.2
  get: ^4.2.4
  http: ^0.13.3
  http_parser: ^4.0.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  listview_utils: ^1.0.0-nullsafety
  loading_overlay: ^0.3.0
  package_info_plus: ^1.0.4
  permission_handler: ^8.1.4
  pref: ^2.4.0
  progress_indicators: ^1.0.0
  rxdart: ^0.27.0
  share_files_and_screenshot_widgets:
    git:
      url: https://github.com/CsabaConsulting/Share-Files-And-Screenshot-Widgets-Flutter.git
  shared_preferences: ^2.0.6
  soundpool: ^2.1.0
  spinner_input:
    git:
      url: https://github.com/CsabaConsulting/spinner_input.git
  sqflite: ^2.0.0+3
  syncfusion_flutter_charts: ^19.2.48
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.9
  wakelock: ^0.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.6
  floor_generator: ^1.1.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.12
  mock_data: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
