name: virtual_velodrome_rider
description: Recording virtual rides as if circling in a Velodrome or on a running track.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_blue: ^0.7.2
  e2e: ^0.2.1
  get: ^3.4.6
  sqflite: ^1.3.0
  flutter_brand_icons: ^1.1.0
  intl: ^0.16.1
  http: ^0.12.2
  url_launcher: ^5.6.0
  shared_preferences: ^0.5.10
  uni_links: ^0.4.0
  http_parser: ^3.1.4
  floor: ^0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  floor_generator: ^0.14.0
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
