name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.55+55

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^4.0.10
  bluetooth_enable: ^0.1.1
  charts_flutter: ^0.10.0
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.2
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  file_picker: ^3.0.2+2
  floor: ^1.1.0
  flutter_blue: ^0.8.0
  flutter_brand_icons: ^1.1.0
  flutter_spinbox: ^0.5.2
  get: ^4.1.4
  http: ^0.13.3
  http_parser: ^4.0.0
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  listview_utils: ^1.0.0-nullsafety
  loading_overlay: ^0.3.0
  meta: ^1.3.0
  permission_handler: ^8.0.0+2
  pref: ^2.2.0
  progress_indicators: ^1.0.0
  rxdart: ^0.26.0
  share_files_and_screenshot_widgets:
    git:
      url: https://github.com/rootasjey/Share-Files-And-Screenshot-Widgets-Flutter.git
  shared_preferences: ^2.0.5
  soundpool: ^2.1.0
  spinner_input: ^0.1.2
  sqflite: ^2.0.0+3
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.3
  wakelock: ^0.5.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  floor_generator: ^1.1.0
  integration_test: ^1.0.2+3
  mockito: ^5.0.9
  mock_data: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
  assets:
    - assets/
