name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.99+99

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.4"

dependencies:
  assorted_layout_widgets: ^5.5.0
  bluetooth_enable:
    git:
      url: https://github.com/CsabaConsulting/bluetooth_enable.git
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.3
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  file_picker: ^4.5.1
  floor: ^1.2.0
  flutter_blue:
    git:
      url: https://github.com/CsabaConsulting/flutter_blue.git
  flutter_circle_color_picker: ^0.3.0
  flutter_layout_grid: ^1.0.6
  flutter_logs: ^2.1.5
  flutter_native_timezone: ^2.0.0
  flutter_spinbox: ^0.8.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  group_button: ^4.8.0
  http: ^0.13.4
  http_parser: ^4.0.0
  internet_connection_checker: 0.0.1+3
  intl: ^0.17.0
  listview_utils: ^1.0.0-nullsafety
  loading_overlay: ^0.3.0
  overlay_tutorial: ^2.2.2
  package_info_plus: ^1.3.1
  permission_handler: 8.1.6
  pref: ^2.5.0
  progress_indicators: ^1.0.0
  rxdart: ^0.27.3
  share_files_and_screenshot_widgets: ^1.0.6
  soundpool: ^2.3.0
  spinner_input:
    git:
      url: https://github.com/CsabaConsulting/spinner_input.git
  sqflite: ^2.0.2
  syncfusion_flutter_charts: ^19.4.56
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  wakelock: ^0.6.1+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.8
  floor_generator: ^1.2.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.16
  mock_data: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
