name: virtual_velodrome_rider
description: Recording virtual rides as if circling in a Velodrome or on a running track.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_blue: ^0.7.2
  e2e: ^0.2.1
  get: ^3.4.6
  sqflite: ^1.3.0
  flutter_brand_icons: ^1.1.0
  strava_flutter: ^1.2.2+61
  intl: ^0.16.1
  path_provider: ^1.6.14
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
