name: Flutter Test & Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      - run: echo 'const STRAVA_SECRET="a";const STRAVA_CLIENT_ID="1";const SUUNTO_SECRET="a";const SUUNTO_CLIENT_ID="a";const SUUNTO_SUBSCRIPTION_PRIMARY_KEY="a";const SUUNTO_SUBSCRIPTION_SECONDARY_KEY="a";const UNDER_ARMOUR_SECRET="a";const UNDER_ARMOUR_KEY="a";const TRAINING_PEAKS_SECRET="a";const TRAINING_PEAKS_CLIENT_ID="a";const GOOGLE_FIT_CLIENT_ID="a";const GOOGLE_FIT_SECRET="a";' > lib/persistence/secret.dart
      - run: flutter test
      - run: flutter build appbundle
