name: Flutter Test & Build
on: [push, pull_request]
jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Mock Secrets File
        run: |
          git clone https://gist.github.com/MrCsabaToth/594df97db65588c2924011d37cca4207
          mv 594df97db65588c2924011d37cca4207/secret.dart lib/
          rm -rf 594df97db65588c2924011d37cca4207/
      - name: Format files
        run: flutter format --line-length 100 --set-exit-if-changed .
      - name: Analyze files
        run: flutter analyze .
      - name: Run the tests
        run: flutter test
      #- name: Build App Bundle (debug)
      #  run: flutter build appbundle
